import type { Diploma, Certification } from '@/lib/types';
import type { Localized } from '@/lib/i18n';

export const diplomas: Localized<Diploma[]> = {
  fr: [
    {
      degree: 'Master 2 en Génie Logiciel',
      school: 'Athénée Saint Joseph Antsirabe',
      location: 'Madagascar',
      year: '2017',
      description: 'Bac + 5 en ingénierie logicielle',
    },
    {
      degree: "Licence professionnelle en développement d'applications informatiques",
      school: 'Athénée Saint Joseph Antsirabe (Bac + 3)',
      location: 'Madagascar',
      year: '2014',
      description: 'Bac + 3 en informatique appliquée',
    },
  ],
  en: [
    {
      degree: "Master's Degree in Software Engineering",
      school: 'Athénée Saint Joseph Antsirabe',
      location: 'Madagascar',
      year: '2017',
      description: '5-year degree in software engineering',
    },
    {
      degree: 'Professional Bachelor\'s in Software Application Development',
      school: 'Athénée Saint Joseph Antsirabe (3-year degree)',
      location: 'Madagascar',
      year: '2014',
      description: '3-year degree in applied computer science',
    },
  ],
};

// Intitulés officiels des cours, gardés dans leur langue d'origine ; seules la date et la durée sont traduites
export const certifications: Localized<Certification[]> = {
  fr: [
    {
      title: 'LangChain avec Python',
      subtitle: 'LLM, RAG et apps IA',
      issuer: 'Udemy',
      instructor: 'Rod Paris',
      date: 'oct. 2026',
      duration: '2,5 h',
      file: '/certifications/langchain-python.pdf',
      verifyUrl: 'https://ude.my/UC-8355d60b-2a0f-4845-b0af-0560fc2981f6',
      group: 'tech',
    },
    {
      title: 'Kubernetes : les bases indispensables pour DevOps',
      issuer: 'Udemy',
      instructor: 'Dirane Willy Tafen',
      date: 'oct. 2026',
      duration: '11 h',
      file: '/certifications/kubernetes-devops.pdf',
      verifyUrl: 'https://ude.my/UC-ec4f958d-1284-4b80-87b7-4dcd018dc2a3',
      group: 'tech',
    },
    {
      title: 'Master LangChain v1 and Ollama',
      subtitle: 'Chatbot, RAG and AI Agents',
      issuer: 'Udemy',
      instructor: 'KGP Talkie',
      date: 'nov. 2025',
      duration: '17,5 h',
      file: '/certifications/langchain-ollama.pdf',
      verifyUrl: 'https://ude.my/UC-5f109e96-8d50-46f9-b36d-d438946ba13e',
      group: 'tech',
    },
    {
      title: 'Llama / Mistral AI',
      subtitle: 'Maîtrisez l\'IA générative open source',
      issuer: 'Udemy',
      instructor: 'Anthony Cardinale',
      date: 'nov. 2025',
      duration: '7 h',
      file: '/certifications/llama-mistral.pdf',
      verifyUrl: 'https://ude.my/UC-387a3e97-02d6-4aac-8269-92ec04776a50',
      group: 'tech',
    },
    {
      title: 'PowerPoint pour les formatrices et formateurs',
      issuer: 'Udemy',
      instructor: 'Pascal Haumont',
      date: 'nov. 2025',
      duration: '1 h',
      file: '/certifications/powerpoint-formateurs.pdf',
      verifyUrl: 'https://ude.my/UC-e1bf4542-3a54-45b6-81e0-809bc4df8015',
      group: 'soft',
    },
    {
      title: 'Éliminez la peur de prise de parole en public',
      issuer: 'Udemy',
      instructor: 'Jamal Lazaar',
      date: 'nov. 2025',
      duration: '1,5 h',
      file: '/certifications/prise-de-parole.pdf',
      verifyUrl: 'https://ude.my/UC-bd61a8b4-a6c1-4a7f-bbaa-3e0c5590ff3e',
      group: 'soft',
    },
  ],
  en: [
    {
      title: 'LangChain avec Python',
      subtitle: 'LLM, RAG et apps IA',
      issuer: 'Udemy',
      instructor: 'Rod Paris',
      date: 'Oct 2026',
      duration: '2.5 h',
      file: '/certifications/langchain-python.pdf',
      verifyUrl: 'https://ude.my/UC-8355d60b-2a0f-4845-b0af-0560fc2981f6',
      group: 'tech',
    },
    {
      title: 'Kubernetes : les bases indispensables pour DevOps',
      issuer: 'Udemy',
      instructor: 'Dirane Willy Tafen',
      date: 'Oct 2026',
      duration: '11 h',
      file: '/certifications/kubernetes-devops.pdf',
      verifyUrl: 'https://ude.my/UC-ec4f958d-1284-4b80-87b7-4dcd018dc2a3',
      group: 'tech',
    },
    {
      title: 'Master LangChain v1 and Ollama',
      subtitle: 'Chatbot, RAG and AI Agents',
      issuer: 'Udemy',
      instructor: 'KGP Talkie',
      date: 'Nov 2025',
      duration: '17.5 h',
      file: '/certifications/langchain-ollama.pdf',
      verifyUrl: 'https://ude.my/UC-5f109e96-8d50-46f9-b36d-d438946ba13e',
      group: 'tech',
    },
    {
      title: 'Llama / Mistral AI',
      subtitle: 'Maîtrisez l\'IA générative open source',
      issuer: 'Udemy',
      instructor: 'Anthony Cardinale',
      date: 'Nov 2025',
      duration: '7 h',
      file: '/certifications/llama-mistral.pdf',
      verifyUrl: 'https://ude.my/UC-387a3e97-02d6-4aac-8269-92ec04776a50',
      group: 'tech',
    },
    {
      title: 'PowerPoint pour les formatrices et formateurs',
      issuer: 'Udemy',
      instructor: 'Pascal Haumont',
      date: 'Nov 2025',
      duration: '1 h',
      file: '/certifications/powerpoint-formateurs.pdf',
      verifyUrl: 'https://ude.my/UC-e1bf4542-3a54-45b6-81e0-809bc4df8015',
      group: 'soft',
    },
    {
      title: 'Éliminez la peur de prise de parole en public',
      issuer: 'Udemy',
      instructor: 'Jamal Lazaar',
      date: 'Nov 2025',
      duration: '1.5 h',
      file: '/certifications/prise-de-parole.pdf',
      verifyUrl: 'https://ude.my/UC-bd61a8b4-a6c1-4a7f-bbaa-3e0c5590ff3e',
      group: 'soft',
    },
  ],
};
